syntax adjusted

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,11 +31,7 @@ jobs:
         - name: "Check if input tag exists"
           id: check_tag
           run: |
-            if ! git show-ref tags/${{ github.event.inputs.tag }}; then
-              echo "Error: Tag ${{ github.event.inputs.tag }} does not exist."; exit 1
-            else
-              echo "Check tag succeeded"
-            fi
+            if ! git show-ref tags/${{ github.event.inputs.tag }} >/dev/null 2>&1; then echo "Error: Tag ${{ github.event.inputs.tag }} does not exist."; else echo "Check tag succeeded"; fi
           shell: bash
 
   # This first job obtains OICD OAUTH token for service principal through API
