da finire

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,10 +22,22 @@ on:
        
           
 jobs:
+  check-tag:
+      name: 'check user tag input'
+      #check if user input tag actually exists
+      runs-on: ubuntu-latest
+      steps:
+        - run: |
+            if ! git show-ref tags/${{ github.event.inputs.tag }}; then
+              echo "Error: Tag ${{ github.event.inputs.tag }} does not exist."
+  	          exit 1
+            fi
+
   # This first job obtains OICD OAUTH token for service principal through API
   get-sp-oauth-token:
     name: 'CI/CD pipeline'
     runs-on: ubuntu-latest
+    needs: check-tag
      # Configure current environment
     environment: ${{ github.event.inputs.environment }}
     outputs:
