Fix tag check and update variable casing in workflows

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,18 +22,20 @@ on:
        
 jobs:
   check-tag:
-      name: 'check user tag input'
+      name: 'Check user tag input'
       #check if user input tag actually exists
       runs-on: ubuntu-latest
+      # In check-tag job, add checkout as first step:
       steps:
+        - uses: actions/checkout@v4
         - name: "Check if input tag exists"
           id: check_tag
           run: |
-              if ! git show-ref tags/${{ github.event.inputs.tag }}; then
-                echo "Error: Tag ${{ github.event.inputs.tag }} does not exist."; exit 1
-  			      else
-  			        echo "Check tag succeeded"
-              fi
+            if ! git show-ref tags/${{ github.event.inputs.tag }}; then
+              echo "Error: Tag ${{ github.event.inputs.tag }} does not exist."; exit 1
+            else
+              echo "Check tag succeeded"
+            fi
           shell: bash
 
   # This first job obtains OICD OAUTH token for service principal through API
@@ -41,7 +43,7 @@ jobs:
     name: 'CI/CD pipeline'
     runs-on: ubuntu-latest
     needs: check-tag
-     # Configure current environment
+    # Configure current environment
     environment: ${{ github.event.inputs.environment }}
     outputs:
       databricks_token_sp: ${{ steps.get_token.outputs.OAUTH_TOKEN }}
@@ -50,7 +52,7 @@ jobs:
         id: get_token
         run: |
           RESPONSE=$(curl --request POST --url ${{ vars.HOST }}'/oidc/v1/token' --user ${{ secrets.CLIENT_ID }}:${{ secrets.CLIENT_SECRET }} --data 'grant_type=client_credentials&scope=all-apis')
-          OAUTH_TOKEN=$(echo $response | jq -r '.access_token')
+          OAUTH_TOKEN=$(echo $RESPONSE | jq -r '.access_token')
           
   # Bundle validation is automatically performed as part of this deployment.
   # If validation fails, this workflow fails.
