syntax adjusted

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,18 +20,21 @@ on:
         required: true
         type: string
        
-          
 jobs:
   check-tag:
       name: 'check user tag input'
       #check if user input tag actually exists
       runs-on: ubuntu-latest
       steps:
-        - run: |
-            if ! git show-ref tags/${{ github.event.inputs.tag }}; then
-              echo "Error: Tag ${{ github.event.inputs.tag }} does not exist."
-  	          exit 1
-            fi
+        - name: "Check if input tag exists"
+          id: check_tag
+          run: |
+              if ! git show-ref tags/${{ github.event.inputs.tag }}; then
+                echo "Error: Tag ${{ github.event.inputs.tag }} does not exist."; exit 1
+  			      else
+  			        echo "Check tag succeeded"
+              fi
+          shell: bash
 
   # This first job obtains OICD OAUTH token for service principal through API
   get-sp-oauth-token:
